### ISSUE TITLE
Transmitter and Receiver succeed even that file doesn't exist

### ISSUE THREAD

**Issue by debugmaster** [thamenato/ufscar-redes2015#16]
Both transmitter and Receiver report error and success after requesting a file that doesn't exist.

Transmitter says: 
receiver(('127.0.0.1', 62706)) requested file test.txt
transmitter>file not found!
transmitter successfully sent file 'test.txt' to receiver(('127.0.0.1', 62706))

Receiver says:
receiver requesting to transmitter(localhost:999) for file test.txt
...E R R O R   f i l e   n o t   f o u n d !
...file test.txt written.

**Comment by ThiagoTioGuedes** [comment]
There was a mistake here. The commit f4d3f39  should be closing the issue #18 not this one. Sorry for the mess
