### ISSUE TITLE
Transmitter timeout needs a maximum number of attempts

### ISSUE THREAD

**Issue by debugmaster** [thamenato/ufscar-redes2015#18]
When a request times out in the receiver, the transmitter will be waiting for ACKs packages. 
It loops forever.

A counter to number of attempts needs to be added for the transmitter too. The counter is zeroed at the beginning of a connection and when an 'ACK' package arrives. The counter increases when the socket times out.

**Comment by ThiagoTioGuedes** [comment]
As seem in the comment above, this issue was actually closed by commit f4d3f39.
